name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      # 第一步：从仓库中检出代码
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 第二步：生成 GitHub 3D Profile 贡献图
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # 第三步：提交并推送更新
      - name: Commit & Push
        run: |
          git config user.name chenzhengduan
          git config user.email code.duan@gmail.com
          git add -A .
          git commit -m "generated"
          git push

      # 第四步：安装 Node.js 和 npm
      - name: Install Node.js and npm
        run: |
          sudo apt-get install -y nodejs npm
          npm install node-fetch@2

      # 第五步：获取 Notion 页面内容并发送到企业微信机器人
      - name: Fetch Notion Page and Send to WeChat Work
        run: |
          node ./fetch-notion.js
